apiVersion: v1
kind: Pod
metadata:
  name: myflask
spec:
  containers:
  - name: myflask
    image: myflask:latest
    # imagePullPolicy: Never
    resources:
      limits:
        memory: "200Mi"
        cpu: "500m"
