apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-selector
  template:
    metadata:
      labels:
        app: multi-container-selector
    spec:
      containers:
        - name: redis-img
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
        - name: myflask-multi-cont-img
          image: myflask-multi-cont:latest
          env:
          - name: NAME
            value: "My name"
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
spec:
  type: NodePort
  ports:
    - nodePort: 30008
      port: 5000
      targetPort: 5000
  selector:
    app: multi-container-selector
