apiVersion: v1
kind: PersistentVolume
metadata:
  name: phpfpm-nginx-pv
  labels:
    type: local
    app: phpfpm-nginx-volume
spec:
  storageClassName: phpfpmstorage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/phpfpm"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpfpm-nginx-pvc
  labels:
    app: phpfpm-nginx-volume
spec:
  storageClassName: phpfpmstorage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: phpfpm-nginx-configmap
data:
  default.conf: |
        server {

            root /var/www/html/phppgadmin;
            index index.php;

            location / {
              try_files $uri $uri/ =404;
            }

            location ~ \.php$ {
                try_files $uri $uri/ =404;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_read_timeout 300;
                proxy_read_timeout 300;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                fastcgi_param DOCUMENT_ROOT $realpath_root;
            }


            client_max_body_size 6m;
            error_log  /var/log/nginx/error.log;
            access_log /var/log/nginx/access.log;
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: phpfpm-nginx-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpfpm-nginx-selector
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpfpm-nginx-selector
        
    spec:
      containers:
        - name: php
          image: php-fpm
          ports:
            - containerPort: 9000
              name: http
              protocol: TCP
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
          imagePullPolicy: Never
          volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: www-storage
            mountPath: /var/www/html/phppgadmin
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /app/* /var/www/html"]
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
          volumeMounts:
          - name: nginx-config-volume
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
          - name: www-storage
            mountPath: /var/www/html/phppgadmin
      volumes:
        - name: www-storage
          persistentVolumeClaim:
            claimName: phpfpm-nginx-pvc
        - name: nginx-config-volume
          configMap:
            name: phpfpm-nginx-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: phpfpm-nginx-service
spec:
  type: NodePort
  ports:
    - nodePort: 30091
      port: 80
      targetPort: 80
  selector:
    app: phpfpm-nginx-selector