# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # _____________  kubmaster  _____________
  config.vm.define "kubmaster" do |kub|
     kub.vm.box = "debian/bookworm64"
     kub.vm.box_check_update = true
     kub.vm.hostname = "kubmaster"
     # kub.vm.provision = "virtualbox"
     kub.vm.box_url = "debian/bookworm64"
     kub.vm.box_check_update = true
     kub.vm.network "private_network", ip: "192.168.56.101"
        
     kub.vm.provider "virtualbox" do |vb|
       vb.name = "kubmaster"
       # vb.gui = false
       vb.memory = "2048"
     end

     kub.vm.provision "shell", inline: <<-SHELL
       echo "START UPDATE SYSTEM ..."
       
       # =======  COMMON  ======= 
       export DEBIAN_FRONTEND=noninteractive   
       apt-get update -y
       apt install -y zstd console-data keyboard-configuration console-setup vim lsb-release gnupg2 apt-transport-https ca-certificates curl software-properties-common
       
       # =======  SSH  =======
       sed -i 's/^#* *\(PermitRootLogin\)\(.*\)$/\1 yes/' /etc/ssh/sshd_config
       sed -i 's/^#* *\(PasswordAuthentication\)\(.*\)$/\1 yes/' /etc/ssh/sshd_config
       systemctl restart sshd.service
       
       # =======  USERS  =======
       echo -e "pwd\npwd" | (passwd vagrant)
       echo -e "pwd\npwd" | (passwd root)
       
       # =======  DOCKER  =======
       curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/debian.gpg
       add-apt-repository -y "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
       apt update -y
       apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
       usermod -aG docker vagrant
       
       # =======  KUBERNETES  ======= (https://www.linuxtechi.com/install-kubernetes-cluster-on-debian/)
       export KUBECONFIG=/etc/kubernetes/admin.conf 
       echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
       curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
       apt update -y
       apt install -y kubelet kubeadm kubectl # sysctl enable kubelet ??
       apt-mark hold kubelet kubeadm kubectl
       swapoff -a
       sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
       systemctl enable kubelet.service
       systemctl restart kubelet.service
       mv /etc/containerd/config.toml /etc/containerd/config.toml.bak
       systemctl enable containerd.service
       systemctl restart containerd.service
       
       # =======  KEYBOARD  =======
       cat > /etc/default/keyboard <<EOF
XKBMODEL="pc105"
XKBLAYOUT="fr"
XKBVARIANT=""
XKBOPTIONS=""    
BACKSPACE="guess"
EOF
       dpkg-reconfigure keyboard-configuration
       service keyboard-setup restart
       echo "KEYMAP=y" >> /etc/initramfs-tools/initramfs.conf
       update-initramfs -u
       
       # =======  BASHRC  =======
       cat >> /root/.bashrc <<EOF
export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -Al'
alias l='ls $LS_OPTIONS -A'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias h='history'
alias b='vim ~/.bashrc'
alias s='source ~/.bashrc'
alias i='vim /etc/network/interfaces'
alias u='apt-get update && apt-get upgrade && apt-get clean'
alias f='findmnt'
EOF
       echo "END UPDATE SYSTEM"
    SHELL
  end
  # _____________  kubmaster  _____________
  
  
  # _____________  kubnode  _____________
  config.vm.define "kubnode" do |kub|
     kub.vm.box = "debian/bookworm64"
     kub.vm.box_check_update = true
     kub.vm.hostname = "kubnode"
     # kub.vm.provision = "virtualbox"
     kub.vm.box_url = "debian/bookworm64"
     kub.vm.box_check_update = true
     kub.vm.network "private_network", ip: "192.168.56.102"
        
     kub.vm.provider "virtualbox" do |vb|
       vb.name = "kubnode"
       # vb.gui = false
       vb.memory = "2048"
     end

     kub.vm.provision "shell", inline: <<-SHELL
       echo "START UPDATE SYSTEM ..."
       
       # =======  COMMON  ======= 
       export DEBIAN_FRONTEND=noninteractive   
       apt-get update -y
       apt install -y zstd console-data keyboard-configuration console-setup vim lsb-release gnupg2 apt-transport-https ca-certificates curl software-properties-common
       
       # =======  SSH  =======
       sed -i 's/^#* *\(PermitRootLogin\)\(.*\)$/\1 yes/' /etc/ssh/sshd_config
       sed -i 's/^#* *\(PasswordAuthentication\)\(.*\)$/\1 yes/' /etc/ssh/sshd_config
       systemctl restart sshd.service
       
       # =======  USERS  =======
       echo -e "pwd\npwd" | (passwd vagrant)
       echo -e "pwd\npwd" | (passwd root)
       
       # =======  DOCKER  =======
       curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/debian.gpg
       add-apt-repository -y "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
       apt update -y
       apt install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
       usermod -aG docker vagrant
       
       # =======  KUBERNETES  ======= (https://www.linuxtechi.com/install-kubernetes-cluster-on-debian/)
       echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
       curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
       apt update -y
       apt install -y kubelet kubeadm kubectl # sysctl enable kubelet ??
       apt-mark hold kubelet kubeadm kubectl
       swapoff -a
       sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
       systemctl enable kubelet.service
       systemctl restart kubelet.service
       mv /etc/containerd/config.toml /etc/containerd/config.toml.bak
       systemctl enable containerd.service
       systemctl restart containerd.service
       
       # =======  KEYBOARD  =======
       cat > /etc/default/keyboard <<EOF
XKBMODEL="pc105"
XKBLAYOUT="fr"
XKBVARIANT=""
XKBOPTIONS=""    
BACKSPACE="guess"
EOF
       dpkg-reconfigure keyboard-configuration
       service keyboard-setup restart
       echo "KEYMAP=y" >> /etc/initramfs-tools/initramfs.conf
       update-initramfs -u
       
       # =======  BASHRC  =======
       cat >> /root/.bashrc <<EOF
export KUBECONFIG=/etc/kubernetes/admin.conf
export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -Al'
alias l='ls $LS_OPTIONS -A'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias h='history'
alias b='vim ~/.bashrc'
alias s='source ~/.bashrc'
alias i='vim /etc/network/interfaces'
alias u='apt-get update && apt-get upgrade && apt-get clean'
alias f='findmnt'
EOF
       echo "END UPDATE SYSTEM"
    SHELL
  end
  # _____________  kubnode  _____________
  
end
