apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-redis-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-redis-project
  template:
    metadata:
      labels:
        app: flask-redis-project
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
        - name: myflask
          image: myflask:latest
          env:
          - name: NAME
            value: "My name"
          ports:
            - containerPort: 5000
          imagePullPolicy: Never
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-redis-project
spec:
  type: NodePort
  ports:
    - nodePort: 30008
      port: 5000
      targetPort: 5000
  selector:
    app: flask-redis-project
