apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config  # Name of the ConfigMap for Nginx configuration
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.php index.html;

        server_name _;

        location / {
          try_files $uri $uri/ =404;
        }
        location ~ \.php$ {
          include fastcgi_params;
          fastcgi_param REQUEST_METHOD $request_method;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          fastcgi_pass 127.0.0.1:9000;
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpfpm-nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpfpm-nginx-selector
  template:
    metadata:
      labels:
        app: phpfpm-nginx-selector
    spec:

      volumes:
      - name: shared-files
      - name: nginx-config-volume
        configMap:
          name: nginx-config

      containers:

        - name: php
          image: php-fpm
          ports:
            - containerPort: 9000
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
          imagePullPolicy: Never
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]

        - name: nginx
          image: nginx
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
          volumeMounts:
            - name: shared-files
              mountPath: /var/www/html
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: phpfpm-nginx-service
spec:
  type: NodePort
  ports:
    - nodePort: 30090
      port: 80
      targetPort: 80
  selector:
    app: phpfpm-nginx-selector