# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.box_check_update = true

   # config.vm.hostname = "myhostname"
   config.vm.define "mydebian"
        
   config.vm.provider "virtualbox" do |vb|
     # vb.name = "myname"
     vb.gui = false
     vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
     echo "START UPDATE SYSTEM ..."
     export DEBIAN_FRONTEND=noninteractive   
     cat > /etc/default/keyboard <<EOF
XKBMODEL="pc105"
XKBLAYOUT="fr"
XKBVARIANT=""
XKBOPTIONS=""    
BACKSPACE="guess"
EOF
     apt-get update -y
     apt install -y zstd console-data keyboard-configuration console-setup vim
     dpkg-reconfigure keyboard-configuration
     service keyboard-setup restart
     echo "KEYMAP=y" >> /etc/initramfs-tools/initramfs.conf
     update-initramfs -u

     sed -i 's/^#* *\(PermitRootLogin\)\(.*\)$/\1 yes/' /etc/ssh/sshd_config
     sed -i 's/^#* *\(PasswordAuthentication\)\(.*\)$/\1 yes/' /etc/ssh/sshd_config
     systemctl restart sshd.service
     echo -e "gizaoui\ngizaoui" | (passwd vagrant)
     echo -e "gizaoui\ngizaoui" | (passwd root)
     useradd -u 1000 -m -d /home/gizaoui gizaoui -s /bin/bash
     echo -e "gizaoui\ngizaoui" | (passwd gizaoui)
  
     cat >> /root/.bashrc <<EOF
export LS_OPTIONS='--color=auto'
eval "$(dircolors)"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -Al'
alias l='ls $LS_OPTIONS -A'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias h='history'
alias b='vim ~/.bashrc'
alias s='source ~/.bashrc'
alias i='vim /etc/network/interfaces'
alias u='apt-get update && apt-get upgrade && apt-get clean'
alias f='findmnt'
EOF
     echo "END UPDATE SYSTEM"

  SHELL
  
end
